
https://www.youtube.com/watch?v=BzcBsTou0C0&t=1s

Neural Networks and Pytorch Introduction P.1:
- Fully connected network all parameters are connected to the next level
- Input->HiddenLv1->HiddenLv2->Output
- Input multiplied by weight then summed with all inputs with Sigma
- Sent to an "Activator" which decides whether to send signal (0, 1)
- 3 blue 1 brown Youtube

In [9]:
import torch

x = torch.Tensor([5, 3])
y = torch.Tensor([2, 1])

print(x * y)


tensor([10.,  3.])


In [10]:
x = torch.zeros([2, 5])
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [11]:
x.shape

torch.Size([2, 5])

In [12]:
y = torch.rand([2, 5])
y

tensor([[0.5704, 0.7220, 0.4442, 0.4521, 0.5154],
        [0.6356, 0.3561, 0.1915, 0.2778, 0.5043]])

In [13]:
"""flatten element"""
y = y.view([1, 10])
y

tensor([[0.5704, 0.7220, 0.4442, 0.4521, 0.5154, 0.6356, 0.3561, 0.1915, 0.2778,
         0.5043]])


https://www.youtube.com/watch?v=i2yPxY2rOzs

Data - Deep Learning and Neural networks with Python and Pytorch P.2:
- pip install torchvision
- neural networks solve vision tasks (tends to be with vision)
- torchvision has data
- out of sample data: data the machine hasn't touched/used before
- BATCH: how much data is fed through at a time (usually 8-64)
- people like base 8 for some reason


In [14]:
import torch
import torchvision
from torchvision import transforms, datasets

In [15]:
"define two different datasets"
train = datasets.MNIST("", train=True, download=True,
                        transform = transforms.Compose([transforms.ToTensor()]))

test = datasets.MNIST("", train=False, download=True,
                        transform = transforms.Compose([transforms.ToTensor()]))

100.1%Extracting MNIST\raw\train-images-idx3-ubyte.gz to MNIST\raw
113.5%Extracting MNIST\raw\train-labels-idx1-ubyte.gz to MNIST\raw
100.4%Extracting MNIST\raw\t10k-images-idx3-ubyte.gz to MNIST\raw
180.4%Extracting MNIST\raw\t10k-labels-idx1-ubyte.gz to MNIST\raw
Processing...
Done!


In [16]:
trainset = torch.utils.data.DataLoader(train, batch_size=10, shuffle=True)
testset = torch.utils.data.DataLoader(test, batch_size=10, shuffle=True)

In [17]:
for data in trainset:
    print(data)
    break

[tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        ...,


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0

In [18]:
x, y = data[0][0], data[1][0]
print(y)

tensor(6)


In [20]:
import matplotlib.pyplot as plt

#plt.imshow(data[0][0])

In [22]:
print(data[0][0].shape)

torch.Size([1, 28, 28])
