In [3]:
"""
https://www.youtube.com/watch?v=BzcBsTou0C0&t=1s

Neural Networks:
- Fully connected network all parameters are connected to the next level
- Input->HiddenLv1->HiddenLv2->Output
- Input multiplied by weight then summed with all inputs with Sigma
- Sent to an "Activator" which decides whether to send signal (0, 1)
- 3 blue 1 brown Youtube
"""

'\nhttps://www.youtube.com/watch?v=BzcBsTou0C0&t=1s\n\nNeural Networks:\n- Fully connected network all parameters are connected to the next level\n- Input->HiddenLv1->HiddenLv2->Output\n- Input multiplied by weight then summed with all inputs with Sigma\n- Sent to an "Activator" which decides whether to send signal (0, 1)\n- 3 blue 1 brown Youtube\n'

In [1]:
import torch

x = torch.Tensor([5, 3])
y = torch.Tensor([2, 1])

print(x * y)


tensor([10.,  3.])


In [5]:
x = torch.zeros([2, 5])
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [6]:
x.shape

torch.Size([2, 5])

In [8]:
y = torch.rand([2, 5])
y

tensor([[0.4872, 0.3275, 0.0502, 0.4357, 0.5117],
        [0.1676, 0.6053, 0.4482, 0.7289, 0.2175]])

In [12]:
"""flatten element"""
y = y.view([1, 10])
y

tensor([[0.4872, 0.3275, 0.0502, 0.4357, 0.5117, 0.1676, 0.6053, 0.4482, 0.7289,
         0.2175]])